### ISSUE TITLE
Open test server

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Hellion#13]
I planning on opening a test server and build a little registration web site to allow people to test the emulator and track the bugs.

Website will be built using bootstrap 3, ASP.NET Core and AngularJS

**Comment by Eastrall** [comment]
Website will be based on something similar to this: http://azmind.com/demo/bootstrap-registration-forms/form-1/index.html

**Comment by davedevils** [comment]
Why not make "official" CMS for the hellion ?
OpenSource too.

**Comment by Eastrall** [comment]
@davedevils That's a good idea! Let's add it to the idea box 😉
