### ISSUE TITLE
Create Release (files ready for "test") ?

### ISSUE THREAD

**Issue by davedevils** [Eastrall/Hellion#19]
I no have see "release" download for people want to test the emulator ...

Maybe you need to make it ?

**Comment by Eastrall** [comment]
I didn't make any releases for now. Every week-updates the develop branch is merged into the master.

You can clone the `master` branch to have a stable release.

**Comment by Eastrall** [comment]
You can now check the available [Releases](https://github.com/Eastrall/Hellion/releases).
