### ISSUE TITLE
NPC Dialog API

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Hellion#20]
Hi everyone! I'm thinking about the NPC dialogs and try to find a better way to implement the dialogs compared to the official files.

So I've been thinking about a ```json```  file format.
We want the emulator to be the most scalable as possible, so we should allow people to implement other languages than English. For exemple: french, german, etc...

So we have now 3 options:

### 1st option

Create a folder for each language

- data/
   - dialogs/
      - en/
      - fr/
      - de/
      - etc...

Inside this folders we will have one dialog file per NPC.

Loading would be: For each NPC loaded, try to load his dialog in the good directory according to the worldserver configuration file.

### 2nd option

Create an unique file containing all dialogs for each language:

- data
   - dialogs
      - en.json
      - fr.json
      - de.json
      - etc...

Loading will be easy, just open the good file according to the worldserver configuration file.

### 3rd option

Create a folder for each language and put several dialogs file in it.

- data/
   - dialogs/
      - en/
          - npcFlaris.json
          - npcOther.json
      - fr/
      - de/
      - etc...

Loading would be: Load every file in the good directory according to the worldserver configuration file.

### 4th option

Create a single npc dialog file per NPC where it will contains every languages. See comment : https://github.com/Eastrall/Hellion/issues/20#issuecomment-271157546

## WorldDialog API

I thought about this kind of structure:

```javascript
{
   "MaFl_NPC":{
      "oral":"TEXT",
      "textIntro":"INTRO",
      "bye":"BYE TEXT",
      "links":[
         {
            "id":"link_id",
            "title":"title",
            "text":"text"
         }
      ]
   }
}
```

Let me explain the structure:

| Key | Description |
|-----|--------------|
| `MaFl_NPC` | This field would be the ID of the NPC |
| `oral` | The oral text |
| `textIntro` | The introduction text when we open a dialog |
| `bye` | The goodbye text (displayed as oral text) |
| `links` | represents the link we can have on the dialog box. Like "Who are you?" ; "Good Bye" ; Etc... |
| `links.id` | ID of the link |
| `links.title` | Title of the link |
| `links.text` | The text displayed when we click on the link. |

## Full example:

```javascript
{
   "MaFl_Eastrall":{
      "oral":"Hello ! Come and see how cool is the Hellion emulator!",
      "textIntro":"Hey! Do you like Hellion?",
      "bye":"Good bye! See you later!",
      "links":[
         {
            "id":"BYE",
            "title":"Bye",
            "text":"Good bye! See you later!"
         },
         {
            "id":"PRESENTATION",
            "title":"Presentation",
            "text":"My name is Eastrall! I'm the creator of Hellion!"
         }
      ]
   }
}
```

If you have any suggestion about this system, feel free to propose 😄

**Comment by nobox14** [comment]
Well, I think the second option is better. It will be more cleaner to have one file for one  langage instead of having hundreds files ( one file for each pnc ). Then, to load files, it's really simple and it's more easy to do a modification.

**Comment by davedevils** [comment]
For me 1st option ...

Because you can edit without reload , and cheak one by one

Because : 

2nd option -> like the official and the real problem is it's very unconfortable to use ... lot's of edit , lot's time lose

3rd option -> good too but if you use international server you need launch more than 1 server ... and more resource load , so if you use little pc very fat for "reload  all data"

**Comment by Eastrall** [comment]
I've forgot to omit a little detail, the loading of dialogs is made only at the startup of the WorldServer.

We can't afford to read a file every time a client open a dialog box. Imagine you have 1000 clients and 500 are requesting a dialog, you will have to do 500 "the same" action. Open the file, read, parse, close. Not very efficient. So the dialogs should be loaded at startup.

I agree that the second option is kinda heavy, because the files will be huge! But, the reading problem could be solved by creating a tool  like a **DialogEditor**?

I like the 4th option of @davedevils. One file per NPC and every language in it. Nice idea 😉

**Comment by davedevils** [comment]
Ho , why not add a "reload files" after ? because if you make a server they can reload all like resources , events , npc , shop will be enormous :+1:

**Comment by Eastrall** [comment]
We could imagine a `/reload [resourceType]` admin command to force the server to reload some data.

**Comment by nobox14** [comment]
The 4rd option is good !

The reload command is a good idea and it will change proprieties in the worldserver but it will not reload the resdata of the user ! So edits will not be affect on the client..

**Comment by zetsumi** [comment]
1st option is better if 1 file equal one NPC.

And you can create subfolder for each region. 
fr/flarine/is.npc for example.

Why do you want use json? You can create GUI for the management NPC and use binary file (fast load) but json can be ok.

**Comment by Eastrall** [comment]
The purpose of using the `json` format is to have a "user-friendly" file instead of a binary file that can only be read using an editor.

**Comment by cataclys** [comment]
The second Option is better to optimize the research of dialogs by an Id

**Comment by Eastrall** [comment]
I was thinking about merge option 1 and 2. For exemple, in the `dialogs/en` folder, you could have:

- `MaFl_Is.json` => dialog for MaFl_Is npc
- `MaDa_All.json` => dialog for all NPC in darkon.

This method allows you to customize your server as you want! Of course I will provide some functions to `split` or `merge` dialogs.

The global method for the loading would be to load every file in the folder. If there is 100, it will load the 100 files. If there is only one for every npc, only one loading will be performed.

**Comment by Eastrall** [comment]
## NPC Dialog API

The system is the following: We would have one folder named `dialogs`. Inside this folder we would have one or more language folders like: `en` / `fr` / `de` / etc...
In those folder you will have one or more files contains one or several NPC dialogs.
for example:

- MaFl_Lui.json => contains only the MaFl_Lui dialog
- MaDa.json => contains only the dialogs of Darkon npcs.

| Key | Description |
|-----|--------------|
| `name` | This field would be the ID of the NPC |
| `oral` | The oral text |
| `textIntro` | The introduction text when we open a dialog |
| `bye` | The goodbye text (displayed as oral text) |
| `links` | represents the link we can have on the dialog box. Like "Who are you?" ; "Good Bye" ; Etc... |
| `links.id` | ID of the link |
| `links.title` | Title of the link |
| `links.text` | The text displayed when we click on the link. |

Example of file:

```javascript
//
// MaFl_Lui dialog
//

{
	"name": "MaFl_Lui",
	"oral": "Come one, come all! Get your supplies here! You're gonna need it!",
	"textIntro": "Going somewhere? You look a little unprepared, so I'd think twice about leaving Flarine without stocking up on supplies. Good thing for you, I'm here. So, whaddya need?",
	"bye": "Don't forget to shop at Handsome Lui's General Shop for your adventuring needs!",
	"links": [
		{
			"id": "PRESENTATION",
			"title": "Who are you?",
			"text": "Who am I? I'm Lui Keraldine, of course. My friends call me Handsome Lui. Since we're not friends, why don't you just call me Lui. If you buy something from my General Store here, I *might* let you call me Handsome.",
		},
		{
			"id": "BYE",
			"title": "Goodbye",
			"text": "Don't forget to shop at Handsome Lui's General Shop for your adventuring needs!"
		}
	]
}
```
