### ISSUE TITLE
First world login bug

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Hellion#22]
I've noticed a regression when the client tries to login to the world server. The client just froze and you need to kill the neuz and try again.

I don't know if it's this problem is on client part or server part.

**Comment by davedevils** [comment]
2 way :  

1 -> client source bug ?

2 -> bad packet sended by server

**Comment by Eastrall** [comment]
I didn't had time to check this out. But I think my neuz compilation went wrong somehow... Because I didn't had the problem and previous releases (update 3 or 4 for example). Since those releases I didn't touch the spawn packet. 

So it's possible that my neuz has a problem

**Comment by Eastrall** [comment]
This issue seems to be resolved. The problem was due to a bad allocation of `neuz.exe`. Seems my computer can't handle small resolutions 😄
