### ISSUE TITLE
Problem recieving packets

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Hellion#32]
There is an error when recieving and dispatching registered packets:

`[Error]: Exception has been thrown by the target of an invocation.`

First thoughts:

It could be an inter-thread problem.
A problem with Ether.Network library.

This problem needs to be solved ASAP.

**Comment by raventh1984** [comment]
You need to drop the tables. Then start the server then the problem is gone.
Its an bug inside the sql Eastrall provided.

**Comment by Eastrall** [comment]
The problem with the database will be fixed in the next update. It's indeed a bug with the SQL file I've provided. I've made a new export for update 10.

**Comment by Yothri** [comment]
Drop the tables? That would result into no accounts being in database.. How to login then? That cant be the solution for now... Or do you mean dropping only a specific table, like characters?

**Comment by Eastrall** [comment]
The problem was that the SQL file provided was outdated. This problem is now solved.
But to explain a little, you had two solutions:

First one was to let the servers create the tables (in fact, at startup, each server will check if the tables have been created, if not the server will create them.)

Second solution, if you have setup your database with the outdated file, was to drop all the tables or at least the `characters` table. And then when you will start your server, it will create the missing table.

As you said, this can't be the solution, that's why I've updated the `sql/hellion.sql` file in commit: https://github.com/Eastrall/Hellion/commit/cdfacbdce28ca5e2c9acbf0a5b615782996515f3

**Comment by Yothri** [comment]
Yeah figured that out just 30 min before your post haha, but anyways thank you for updating the hellion.sql now. 

I am very interested in this project, i am also very experienced with C# so i will study your source code and maybe help with some pull requests or so :)

Great project !

**Comment by Eastrall** [comment]
Feel free to contribute! That's always nice to have people that have an experience with C#. If you see things that could be done on a different way, please open an issue to share you thoughts 😄

**Comment by Yothri** [comment]
Sure, will do so 👍 

Keep up the good work mate ;)

**Comment by Eastrall** [comment]
After review of this bug, it looks like that a normal problem.
This error occurs when there is an unhandled exception during the packet handling. Since we are using reflection, we don't know where the error comes from.

I've changed the logger output to display the `InnerException` and we can now track the bugs.
