### ISSUE TITLE
Hostname in ISC configuration

### ISSUE THREAD

**Issue by Almewty** [Eastrall/Hellion#41]
I am currently trying to spin up the Servers in Docker instances. I want to run a separate container for every Server (Login/Cluster/World).
The problem I encountered is that I can't specify a hostname for the Cluster ISC configuration under IP.
The error message is:
`[Error]: Cannot connect to ISC. An invalid IP address was specified.`

It seems like `NetClient.Connect` in [ClusterServer.cs](https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.Cluster/ClusterServer.cs#L179) only accepts IP addresses.
Same with the WorldServer.

I added the ability to specify a hostname in my fork at [isc-hostname](https://github.com/Almewty/Hellion/tree/isc-hostname) but I don't think this is the best solution for the problem, thus no pull request for now.

The requirement to specify an IP address makes it kinda cumbersome for Docker. I would try to implement it myself, but I am not sure how to approach it.

**Comment by Eastrall** [comment]
I never tried to run the emulator in a docker instance, but if I understand the problem correctly, you need to specify a host name instead of a IP address to run the servers in a docker instance?

**Comment by Almewty** [comment]
Yeah that's it.
I need this
`  "isc": {
    "ip": "loginserver",
    "port": 15000,
    "interPassword": "-"
  }`
in my cluster.json instead of a fixed IP address

**Comment by Eastrall** [comment]
Oh I see... Maybe what we could do, is a method somewhere in the `Hellion.Core.Network` assembly that can detect if the ip address is a real IP or a hostname. Something like:

```c#
public string GetIpAddressFromHostName(string hostName)
{
    if (hostName is not an IP address)
    {
         // Returning the good IP address
         return Dns.GetHostEntryAsync(hostName).Result.AddressList.First().ToString();
    }

    return hostName; // simply return the hostName because it's already an IP. (has the format XX.XX.XX.XX for example)
```

Then we would call this method to setup our server configuration

**Comment by Almewty** [comment]
Sounds like a good plan.

Checking if the hostname is an IP Address is not required. The documentation for [GetHostEntryAsync](https://msdn.microsoft.com/en-us/library/hh194305(v=vs.110).aspx) states that it accepts IP Addresses too and a quick test shows that it works with IP Addresses.

**Comment by Eastrall** [comment]
Oh yes, I didn't saw the parameter name `hostNameOrAddress`. Let me know if you came up with something that work on docker and windows/linux.

And thank you for testing the emulator on docker!

**Comment by Almewty** [comment]
I tried to implement it, but I can't get the `Dns` class to work in the `Hellion.Core` project.
The `Dns` class needs `System.Net.NameResolution` but it does not support .NET4.5 (only .NET4.6 I think?)

I don't really have any experience with dotnet core (and it's json project files) so help would be appreciated.

**Comment by Eastrall** [comment]
Remember that the Hellion.Core targets two framework:
- .NET Core : represented by the `netstandard1.6` in the `project.json` file.
- .NET Framework 4.5 : represented by the `net45` in the `project.json` file.

In the .NET Core doc, the `GetHostEntryAsync` method is in the `System.Net` namespace, but in the `System.Net.NameResolution.dll` assembly. (https://docs.microsoft.com/en-us/dotnet/core/api/system.net.dns)

For the .NET 4.5 it's ok, it is located in the `System.Net` namespace and in the `System.dll` assembly. So you don't need to do anything in the .NET 4.5 framework.

What you need to do to fix this is to add the correct assembly in the `netstandard1.6` dependencies. You already have your assembly name :wink: `System.Net.NameResolution`.

Once you add it to the dependendies, you need to restore the packages and it should work without problems.

**Comment by Almewty** [comment]
So I created a pull request for this #42 
I tested it on linux and on linux in Docker. I can't test on Windows right now. Seems to work fine.

Feel free to give feedback on the naming.

**Comment by Eastrall** [comment]
PR #42 has been merged. Everything was OK! Working on Windows. Thank you for your contribution!
