### ISSUE TITLE
Move data structures to Hellion.Core

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Hellion#47]
We should move some structures to the `Hellion.Core` project.

- `ItemData.cs` : https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/ItemData.cs
- `MonsterData.cs` : https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/MonsterData.cs
- `SkillData.cs` : https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/SkillData.cs
- `SkillLevelData.cs`: https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/SkillLevelData.cs
- `JobData.cs` : https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/JobData.cs
- `NPCData.cs` : https://github.com/Eastrall/Hellion/blob/develop/src/Hellion.World/Structures/NPCData.cs

----

By moving this files, we can use them in other projects, like tools.

**Comment by Hazzer76k** [comment]
Yes, useful moving ! 
For Pang it will be really necessary ASAP I think ! :)

**Comment by Eastrall** [comment]
Solved in https://github.com/Eastrall/Hellion/commit/7c048b316e771b26a16e98651b0f832c1bde4a4e
